name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - 
        name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag dominix694/chatgpt-next-web-visionary:latest \
            --push .
      -
          name: Deploy to Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            port: ${{ secrets.SERVER_SSH_PORT }}
            script: |
              docker pull dominix694/chatgpt-next-web-visionary:latest
              docker stop chatgpt-next-web-visionary || true
              docker rm chatgpt-next-web-visionary || true
              docker run -d --name chatgpt-next-web-visionary \
                            --restart unless-stopped \
                            -p 16941:3000 \
                            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                            -e OPENAI_ORG_ID=${{ secrets.OPENAI_ORG_ID }}
                            -e CODE=${{ ${{ secrets.ACCESS_CODE }} }} \
                            -e HIDE_USER_API_KEY=1 \
                            dominix694/chatgpt-next-web-visionary:latest
